import React from 'react'
import "./Courses.css"

import Card from "./Card"
export default function Courses() {

  let CoursesData = [
    {
      Banner: "placeholder.jpg",
      Category: "Core Programming",
      CourseTitle: "Complete Basic Python",
      CourseDescription: "lorem",
      CoursePrice: "12000",
      CourseDuration: "12Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "Core Programming",
      CourseTitle: "Advanced Java",
      CourseDescription: "lorem",
      CoursePrice: "15000",
      CourseDuration: "20Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "Core Programming",
      CourseTitle: "C++ for Beginners",
      CourseDescription: "lorem",
      CoursePrice: "10000",
      CourseDuration: "15Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "Core Programming",
      CourseTitle: "Data Structures and Algorithms",
      CourseDescription: "lorem",
      CoursePrice: "18000",
      CourseDuration: "25Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "Core Programming",
      CourseTitle: "Mastering SQL",
      CourseDescription: "lorem",
      CoursePrice: "12000",
      CourseDuration: "18Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "Full Stack",
      CourseTitle: "MERN Stack Development",
      CourseDescription: "lorem",
      CoursePrice: "25000",
      CourseDuration: "40Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "Full Stack",
      CourseTitle: "Angular and Node.js",
      CourseDescription: "lorem",
      CoursePrice: "22000",
      CourseDuration: "35Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "Full Stack",
      CourseTitle: "React and Spring Boot",
      CourseDescription: "lorem",
      CoursePrice: "20000",
      CourseDuration: "30Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "Full Stack",
      CourseTitle: "Vue.js and Laravel",
      CourseDescription: "lorem",
      CoursePrice: "18000",
      CourseDuration: "25Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "Full Stack",
      CourseTitle: "Full Stack Web Development",
      CourseDescription: "lorem",
      CoursePrice: "28000",
      CourseDuration: "45Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "AI",
      CourseTitle: "Machine Learning with Python",
      CourseDescription: "lorem",
      CoursePrice: "20000",
      CourseDuration: "30Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "AI",
      CourseTitle: "Deep Learning Fundamentals",
      CourseDescription: "lorem",
      CoursePrice: "25000",
      CourseDuration: "40Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "AI",
      CourseTitle: "Natural Language Processing",
      CourseDescription: "lorem",
      CoursePrice: "18000",
      CourseDuration: "25Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "AI",
      CourseTitle: "Computer Vision with OpenCV",
      CourseDescription: "lorem",
      CoursePrice: "22000",
      CourseDuration: "35Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "AI",
      CourseTitle: "Reinforcement Learning",
      CourseDescription: "lorem",
      CoursePrice: "20000",
      CourseDuration: "30Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "Non-IT",
      CourseTitle: "Financial Accounting",
      CourseDescription: "lorem",
      CoursePrice: "15000",
      CourseDuration: "20Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "Non-IT",
      CourseTitle: "Marketing Management",
      CourseDescription: "lorem",
      CoursePrice: "12000",
      CourseDuration: "18Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "Non-IT",
      CourseTitle: "Human Resource Management",
      CourseDescription: "lorem",
      CoursePrice: "10000",
      CourseDuration: "15Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "Non-IT",
      CourseTitle: "Business Communication",
      CourseDescription: "lorem",
      CoursePrice: "8000",
      CourseDuration: "12Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "Non-IT",
      CourseTitle: "Project Management",
      CourseDescription: "lorem",
      CoursePrice: "18000",
      CourseDuration: "25Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "Core Programming",
      CourseTitle: "Advanced C++",
      CourseDescription: "lorem",
      CoursePrice: "16000",
      CourseDuration: "22Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "Full Stack",
      CourseTitle: "Django and React",
      CourseDescription: "lorem",
      CoursePrice: "24000",
      CourseDuration: "38Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "AI",
      CourseTitle: "Artificial Intelligence Fundamentals",
      CourseDescription: "lorem",
      CoursePrice: "15000",
      CourseDuration: "20Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "Non-IT",
      CourseTitle: "Digital Marketing",
      CourseDescription: "lorem",
      CoursePrice: "14000",
      CourseDuration: "18Hr",
      CourseLanguage: "English",
    },
    {
      Banner: "placeholder.jpg",
      Category: "Core Programming",
      CourseTitle: "Mastering JavaScript",
      CourseDescription: "lorem",
      CoursePrice: "18000",
      CourseDuration: "25Hr",
      CourseLanguage: "English",
    },
  ];


  return (
    <div>
        <center>
            <h1>Courses</h1>
            {CoursesData.map((e,i)=>
              <Card key = {i} e = {e} />
            )}
        </center>
    </div>
  )
}
